### ISSUE TITLE
Train a different Reading Order Prediction Module

### ISSUE THREAD

**Issue by maurovit** [chongzhangFDU/ROOR#1]
Hello,congratulations for your great work. I'm wondering if the code can be reused to train a different ROP model than LayoutLMv3 (which can cause issues from license point of view). Do you have any suggestions?

Thank you 🙂

**Comment by chongzhangFDU** [comment]
The code and dataset can be directly used for non-commercial research purpose, with the citation of our papers. 
For commercial use, please send an application letter to the authors (chongzhang20@fudan.edu.cn) to apply for commercial purposes usage, including your company, business scope, the specific usage, etc. You will be granted to reuse the code after your letter has been received and approved.

**Comment by chongzhangFDU** [comment]
Considering that the issue proposer has no further requests, the issue will be closed.
