### ISSUE TITLE
Can use GeolayoutLM for rop?

### ISSUE THREAD

**Issue by CourageKeenTriumph** [chongzhangFDU/ROOR#4]
May I ask if the ROP model can only use the v3 model? Or is it necessary to modify the code yourself if using the Geo version?

**Comment by chongzhangFDU** [comment]
For the ROP task, Currently the repository only includes the code implementation of the proposed relation-extraction-based model based on LayoutLMv3. It is necessary to modify the code if you want to use GeoLayoutLM as the encoder in the relation-extraction-based model.
